name: oxid module tests

on: [push]

jobs:
  stand_alone_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Validate composer.json
      run: composer validate
    - name: validate php syntax
      run: find . -not -path "./vendor/*" -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
    - name: install phpcs
      run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
    - name: phpcs psr12
      run: php phpcs.phar -n --standard=PSR12 --extensions=php --ignore=vendor .
#    - name: phplint, phpmd ...
  tests:
    needs: stand_alone_checks
    strategy:
      matrix:
        php: [7.1, 7.2]
        oxid: [6.1, 6.2-rc, dev-master]
        exclude:
          - oxid: dev-master
            php: 7.1
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: oxid
        ports:
          - 3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    runs-on: ubuntu-latest
    container:
      image: oxidprojects/oxid-test:v3_${{matrix.oxid}}_php${{matrix.php}}
    env:
      MODULE_NAME: oxps/creditpass
    steps:
    - uses: actions/checkout@v1
    - name: route db from socket to port
      run: bash /var/www/oxideshop/scripts/routeDbfromSocketToPort.sh
    - name: setup oxid
      run: bash /var/www/oxideshop/scripts/setup.sh
    - name: runt tests
      run: |
        MD=$(pwd)
        cd /var/www/OXID/
        vendor/bin/runtests